# Generated by Django 3.0.8 on 2020-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileup',
            field=models.CharField(max_length=60),
        ),
    ]
