# Generated by Django 3.0.8 on 2020-09-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200908_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.BigIntegerField()),
            ],
        ),
    ]
