# Generated by Django 3.0.8 on 2020-09-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ajax'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ajax',
            new_name='ajaxdatas',
        ),
    ]
